### ISSUE TITLE
windows_2016_docker.json: unknown configuration key: "post_shutdown_delay"

### ISSUE THREAD

**Issue by TheBigBear** [StefanScherer/windows-docker-machine#14]
when running 
```
packer validate virtualbox-iso windows_2016_docker.json
```
I get a weird error msg:
```
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-iso'. 1 error(s) occurred:

* unknown configuration key: "post_shutdown_delay"
```
but the cmd is valid and I can't see anything wrong with it.

my version of packer is recent:
```
packer --version
1.1.2
```

**Comment by StefanScherer** [comment]
Hi @TheBigBear 
hm, do you mean the template in packer-windows?
That repo has a small AppVeyor CI pipeline that validates the templates.

I've checked in locally and it validates fine for me.
```
$ packer validate --only virtualbox-iso windows_2016_docker.json 
Template validated successfully.

$ packer version
Packer v1.1.2
```

That keyword is documented here https://www.packer.io/docs/builders/virtualbox-iso.html#post_shutdown_delay

**Comment by TheBigBear** [comment]
@StefanScherer yes, sorry, just noticed I misfiled this issue, so sorry, should of course have been in the packer-windows templates. 

I had a similar one, for which I just logged another issue in the right repo and there the 'solution' was to have the keyword in the right section. will investigate a bit more, but it most definitely fails here.
the other issue is this one https://github.com/StefanScherer/packer-windows/issues/60

**Comment by TheBigBear** [comment]
@StefanScherer OK, that really bugged me that it tested OK for you, but not for me.

So today I moved everything over to a windows 10 pro machine and re-started the process, and voila, the json files validate and all is well.

Looks like there is at least three differences between mac os x binaries and brew mac os x binaries and how they validate the same json files.

Will report those findings upstream, sorry to have pointed at your 'innocent' json files.
