### ISSUE TITLE
Non windows input encoding

### ISSUE THREAD

**Issue by vors** [StefanScherer/windows-docker-machine#19]
Thank you for the great tool and tutorial! I was able to get up an running very smoothly with mac and  VirtualBox.

After running `docker run -it microsoft/windowsservercore powershell`
I noticed few keyboard problems.
1) when I'm trying to type non-English characters (Cyrillic) it displayes `???`  I.e.

```
PS C:\> ?^??^????^??^?
```

2) If I try to run another `powershell` instance from it, stdio redirection looks broken and I cannot type in the second one.

**Comment by StefanScherer** [comment]
Hey @vors,
Thank you.
This looks like a terminal problem. I've added some tests in [dockerfiles-windows/unicode](https://github.com/StefanScherer/dockerfiles-windows/tree/master/unicode).
Printing Unicode text in container without `-t` option seems to work. The problem occurs when you run a container in a pseudo TTY with `-t`.

**Comment by vors** [comment]
Confirming, without `-t` it does work, but the whole UX without `-t` is more broken :(
1) Tab completion doesn't work
2) Up arrow doesn't get previous commands

**Comment by vors** [comment]
One more observation: pasting long commands when `-t` is used corps the pasted command around 40 chars.

**Comment by StefanScherer** [comment]
Yes, it‘s a known bug pasting more than 50 characters. See eg. https://github.com/moby/moby/issues/29646

Have you looked in moby/moby github repo if there is an issue for the unicode problem?

**Comment by vors** [comment]
No, sorry, I'm pretty new to all these tools, so didn't yet figure out the right repos. Thank you for the pointer.
While trying to run python2 in the container, I hit

```
LookupError: unknown encoding: cp65001
```

Which suggests that encoding problem may be due to this non-standart cp65001 encoding. I will try to play with it.

**Comment by vors** [comment]
Let's close the issue, since I got answers to my newbie questions :)
