### ISSUE TITLE
[question] switchDaemon to linux

### ISSUE THREAD

**Issue by stoffeastrom** [StefanScherer/windows-docker-machine#21]
Hi, thanks for these vm's! They are awesome 💥 

I have question though :)

Is it possible to easily switch the daemon to run linux on the windows docker host?

**Comment by StefanScherer** [comment]
Thanks. 
You mean running LCOW in the Windows VM?
I also thought about this. 
With the 1709 or insider it should be possible. 
Maybe we should integrate some scripts from https://github.com/StefanScherer/docker-windows-box/blob/master/lcow/README.md here to have the LinuxKit and latest docker from master installed. 
Maybe another ‚machine‘ with name ‚lcow‘ ?

**Comment by stoffeastrom** [comment]
Yes, I meant LCOV in the Windows VM

That would be really cool!!!!

That would be even easier just switching to that machine 👍  good thinking

**Comment by StefanScherer** [comment]
Here it is, #22 adds the "lcow" machine.
I've tested it with a Windows Server 1709 machine, but an Insider should do it as well.
