### ISSUE TITLE
stuck on 'vmware-iso: Running'

### ISSUE THREAD

**Issue by tahztest** [StefanScherer/windows-docker-machine#25]
Hey,

After following up to this stage:

```
$ git clone https://github.com/StefanScherer/packer-windows
$ cd packer-windows

$ packer build --only=vmware-iso windows_2016_docker.json
```

It gets to the point where the windows vm displays the cmd with:

`Press Ctrl-Alt-Del to unlock`

And the packer script repeatedly prints:

```
==> vmware-iso: Provisioning with powershell script: ./scripts/docker/docker-pull.ps1
    vmware-iso: Installing microsoft/windowsservercore ...
    vmware-iso: Running
    vmware-iso: Running
    vmware-iso: Running
    vmware-iso: Running
    vmware-iso: Running
```

Any idea on what I could be missing here? It hasn't created the  'windows_2016_docker_vmware.box' file which is why the following command shows an error:

```
$ vagrant box add windows_2016_docker windows_2016_docker_vmware.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'windows_2016_docker' (v0) for provider:
    box: Downloading: windows_2016_docker_vmware.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/name/stackstorm-project/windows-docker/packer-windows/windows_2016_docker_vmware.box
```

Note: I am using Mac Sierra 10.12.6

**Comment by tahztest** [comment]
Got the box downloaded via this pull request. https://github.com/StefanScherer/windows-docker-machine/pull/24

**Comment by StefanScherer** [comment]
Glad you found a way. A packer build normally takes some time, these "Running" messages are normal as the provision script pulls the windowsservercore base image in the background. So if you try to build the box yourself you just have to be more patient ;-)
