### ISSUE TITLE
Script win.updates.ps1 / issue cant build windows_2016_docker.json

### ISSUE THREAD

**Issue by averlius** [StefanScherer/windows-docker-machine#29]
Getting a couple of errors when I try to run this command
 packer build --only=vmware-iso windows_2016_docker.json

<img width="968" alt="screen shot 2018-04-02 at 2 14 34 pm" src="https://user-images.githubusercontent.com/2643937/38213965-57483706-3680-11e8-8d02-cf110f729673.png">
<img width="960" alt="screen shot 2018-04-02 at 2 13 36 pm" src="https://user-images.githubusercontent.com/2643937/38213967-57707c52-3680-11e8-9de0-710593822f8c.png">

Also it seems that the command gets inside a loop and never gets out.
<img width="675" alt="screen shot 2018-04-02 at 2 15 57 pm" src="https://user-images.githubusercontent.com/2643937/38214003-782c5d30-3680-11e8-82b7-44bd1dabda54.png">

Any ideas?

**Comment by StefanScherer** [comment]
Looks like a network problem contacting the Windows update server. 
Are you running this behind a Corporate network blocking these external servers?

**Comment by StefanScherer** [comment]
Closing, seems like a network problem.
