### ISSUE TITLE
"IP address not set" if --provider virtualbox is not given

### ISSUE THREAD

**Issue by jakepetroules** [StefanScherer/windows-docker-machine#3]
I see:

    opts.on("--provider PROVIDER", String, "") do |provider|

This means that if you don't explicitly pass `--provider virtualbox` to `vagrant up`, the Docker machine will show "IP address not set" and can't be communicated with, even if the default provider is VirtualBox and everything else otherwise completes successfully. Can you detect the provider that is *actually* used instead?

**Comment by StefanScherer** [comment]
I haven't found a better way to detect the provider. I don't remember if you have to pass --provider virtualbox only for the first vagrant up.

**Comment by StefanScherer** [comment]
@jakepetroules could you try out the `Vagrantfile` of pull request #4?
I don't have a VirtualBox basebox right now and my machines always have both VMware and VirtualBox installed with VMware as the default, so it's difficult for me to check if that would be a solution.
