### ISSUE TITLE
Does not work with latest Insider (17650) builds

### ISSUE THREAD

**Issue by BradRoot** [StefanScherer/windows-docker-machine#32]
Attempted to run packer-windows with Windows Server LTS (17650) and the checksums don't make. Could not find a matching checksum in any of the .json files within packer-windows. Doesn't appear older Insider builds are available from the download site, either:

broot-mac:packer-windows broot$ packer build --only=vmware-iso windows_2019_docker.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: https://software-download.microsoft.com/db/Windows_InsiderPreview_Server_vNext_en-us_17639.iso
    vmware-iso: Error downloading: checksums didn't match expected: ab5a4980d4a7b8e9028124aef7b2a01ed85b3e32762d8bf15ed21b991f63db6f
==> vmware-iso: ISO download failed.
Build 'vmware-iso' errored: ISO download failed.

**Comment by StefanScherer** [comment]
You have to download the ISO manually and also calculate the checksum if no SHA256 checksum is provided by Microsoft. The download link in the packer template is only a hint, there is no direct download link available.

```
packer build --only=vmware-iso \
  --var iso_url=./path/to/17650.iso \
  --var iso_checksum=... \
  --var iso_checksum_type=sha256 \
  windows_2019_docker.json
```

**Comment by BradRoot** [comment]
Worked great, thanks!
