### ISSUE TITLE
access into the docker 

### ISSUE THREAD

**Issue by ybello33** [StefanScherer/windows-docker-machine#33]
Hi
I have created the VM 
can someone tell me how do i access into it ?
i can RDP it but i don't have the user/pass even if i create new one inside the vm it's still not working 

please advise

**Comment by StefanScherer** [comment]
You can use `vagrant rdp` with user `vagrant` and password `vagrant`. This is the default for all Vagrant boxes.

**Comment by ybello33** [comment]
Thanks a-lot 
this is a great project -- really
