### ISSUE TITLE
Documentation needs to be updated for 2019

### ISSUE THREAD

**Issue by ngrigoriev** [StefanScherer/windows-docker-machine#41]
First of all, thanks for the great project! :)

I have attempted the "easy way" and used pre-packaged 2019-box machine instead of building one. 

I have found that the default images like the one mentioned in the README did not work:

`$ docker run -it -v C:$(pwd):C:$(pwd) microsoft/windowsservercore powershell
docker: Error response from daemon: CreateComputeSystem 3688a0c2b55fe5cc3c7a121138d6c711eba35e94d7fa312726971436ad5ee056: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"3688a0c2b55fe5cc3c7a121138d6c711eba35e94d7fa312726971436ad5ee056","Owner":"docker","VolumePath":"\\\\?\\Volume{4fea9bc8-62b4-4c5e-a62f-a8cb29ca9372}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\3688a0c2b55fe5cc3c7a121138d6c711eba35e94d7fa312726971436ad5ee056","Layers":[{"ID":"4560e28f-cce3-5587-88e4-b1d5fb26663d","Path":"C:\\ProgramData\\docker\\windowsfilter\\a1d31746d217a068e9563635b64f103371010f686058699170fce7ccfc916b59"},{"ID":"2e7685ca-6a6a-5cbc-baf8-276a9a626d89","Path":"C:\\ProgramData\\docker\\windowsfilter\\afda31f2bcb3d86680cdadd4b662f0b6954a83f6354d165c2f1d55afe1bc8556"}],"HostName":"3688a0c2b55f","MappedDirectories":[{"HostPath":"c:\\users\\nik\\git\\windows-docker\\windows-docker-machine","ContainerPath":"c:\\users\\nik\\git\\windows-docker\\windows-docker-machine","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["B6B9B423-FF98-4005-B6E8-9D8F1F99F1D7"],"AllowUnqualifiedDNSQuery":true}).`

However, everything is fine with the machine:

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.15)
  Go version:       go1.10.6
  Git commit:       1ac774dfdd
  Built:            02/10/2019 04:13:25
  OS/Arch:          windows/amd64
  Experimental:     false
```

And your test "whoami" image worked fine too.

It seems that with 2019 windows one has to use more recent base images. I went to https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server and then attempted to use "mcr.microsoft.com/windows/servercore:ltsc2019" image - and it worked fine. Same for "mcr.microsoft.com/windows/nanoserver:1809".

Maybe the docs could be updated to reflect this incompatibility?

**Comment by StefanScherer** [comment]
Thanks @ngrigoriev you are right, the image names have changed to mcr. 
Looks like the readme needs some polish.

**Comment by StefanScherer** [comment]
Fixed with https://github.com/StefanScherer/windows-docker-machine/commit/205aa46cf59b1c976ab62f7e777f1c64549c34de
