### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by buu700** [StefanScherer/windows-docker-machine#46]
This might be a stupid question, but how does licensing Windows for the VM work here? I installed the prebuilt 2019-box image from Vagrant Cloud on macOS and it seems to be working perfectly, but I was never asked for a license key.

Is this a trial version that will stop working at some point? Or is Windows Server free for local development purposes or something, and it's on users to follow the honor system and purchase a license if they know they need one?

Just a bit confused about whether there's anything I need to do outside of what's in the readme to stay above board (and not have this setup unexpectedly die on me), and Microsoft's website hasn't made things any clearer.

**Comment by StefanScherer** [comment]
The 2019-box pulls this Vagrant box https://app.vagrantup.com/StefanScherer/boxes/windows_2019_docker
It is an Enterprise Eval and will expire. 
Build your own Vagrant box with Packer and a valid license.

**Comment by buu700** [comment]
Got it, thanks!
