### ISSUE TITLE
'not enough space on the disk' error on pulling large image

### ISSUE THREAD

**Issue by bilke** [StefanScherer/windows-docker-machine#48]
I am on Mac and I am on the `2019-box` and I switched my docker context to it. Now I want to pull a large image:

```
docker pull stabletec/build-core:windows-msvc
```

But it fails with a disk space error:

```
windows-msvc: Pulling from stabletec/build-core
65014b3c3121: Already exists
266cffe9d908: Already exists
d8f0e6ed0eb7: Pull complete
d4ef2088e7d6: Pull complete
4c7b07939733: Pull complete
2ecd3ecc40b4: Pull complete
86ba088da90c: Pull complete
014b1ef479aa: Pull complete
555c96118075: Extracting [==================================================>]  1.579GB/1.579GB
b237ad222d9e: Download complete
7b00c157abc5: Download complete
fde9c418b037: Download complete
443d69f9e5f9: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2019-07-09T14:16:21-07:00" level=error msg="hcsshim::ImportLayer failed in Win32: There is not enough space on the disk. (0x70) path=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\1d1f81b5c26269532b49444b6c0e82a5d0dbe148c864781ee01ddf5eb0fb868d folder=C:\\ProgramData\\docker\\tmp\\hcs754397167"
hcsshim::ImportLayer failed in Win32: There is not enough space on the disk. (0x70) path=\\?\C:\ProgramData\docker\windowsfilter\1d1f81b5c26269532b49444b6c0e82a5d0dbe148c864781ee01ddf5eb0fb868d folder=C:\ProgramData\docker\tmp\hcs754397167
```

I already expanded the `Disk image size` in the Docker Desktop preferences to 128 GB. Is there anything else I can do?

Thanks!

BTW: Cool project!!

**Comment by StefanScherer** [comment]
Thanks 😊

The option in Docker Desktop does not increase the disk size in the Vagrant VM. 

As it‘s time for a rebuild of the base VM after another patch Tuesday the easiest thing would be to increase disk size in the packer build for the 2019-box https://github.com/StefanScherer/packer-windows/blob/my/windows_2019_docker.json#L159
I‘ll try to kick off a build later today.

**Comment by StefanScherer** [comment]
@bilke should be fixed with https://app.vagrantup.com/StefanScherer/boxes/windows_2019_docker/versions/2019.07.11
