### ISSUE TITLE
Having trouble adding box added after using vagrant

### ISSUE THREAD

**Issue by rroman81** [StefanScherer/windows-docker-machine#51]
Based on the instructions,  I have cloned the packer-windows repository and ran the commands:
```sh
vagrant box add windows_2019_docker windows_2019_docker_virtualbox.box --force
```
However, when navigating to the windows-docker-machine and attempting to run "vagrant up --provider virtualbox_dekstop windows_2019_docker", I get an error that machine does not exist for this environment.

Furthermore, when working a bit further, i went back to packer-windows folder, and ran "vagrant init windows_2019_docker" to add to the vagrantfile (maybe wrong repo), but when I instatiate it, i still do not see it under "docker context ls" command.  

Instructions need some clarification for sure.

**Comment by StefanScherer** [comment]
When you clone the packer-windows repo you also need `packer` installed to build the base vagrant box from an Windows Server ISO file. 

As a quick start if you don‘t want to build your own vagrant box and just use the one that I‘ve created and uploaded to Vagrant Cloud, then skip ahead to https://github.com/StefanScherer/windows-docker-machine/blob/master/README.md#create-the-docker-machine
and use the `2019-box`. This references the box in Vagrant Cloud and it gets downloaded and added automatically for you.

**Comment by ajith-joseph** [comment]
On my Mac, I did
$ git clone https://github.com/StefanScherer/windows-docker-machine
$ cd windows-docker-machine
$ vagrant up --provider virtualbox 2019-box
However 'docker context ls' does not show '2019-box'. It shows only the default one that was there before.
Any idea why?

**Comment by StefanScherer** [comment]
@ajith-joseph please open a new ticket and paste the output of the whole `vagrant up --provider virtualbox 2019-box` command.
I've tried it today and it works for me. We can try to figure out where the problem is in that new ticket.
