### ISSUE TITLE
Virtualbox customization --clipboard renamed in version 6.1

### ISSUE THREAD

**Issue by ghost** [StefanScherer/windows-docker-machine#54]
The Virtual box `--clipboard` command was renamed in version 6.1 to `--clipboard-mode`

The vagrant up command fails with error:

==> 2019-box: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "<vm>", "--clipboard", "bidirectional"]

Stderr: Oracle VM VirtualBox Command Line Management Interface Version 6.1.2
(C) 2005-2020 Oracle Corporation
All rights reserved.

**Comment by StefanScherer** [comment]
That's fixed in the latest Vagrant boxes from Vagrant Cloud.
There was some noise between 6.1.x and now 6.1.2.
I'll close this. Let me know if you still encounter problems.
