### ISSUE TITLE
Support for virtualbox 6.1.6

### ISSUE THREAD

**Issue by mohammadchehab** [StefanScherer/windows-docker-machine#61]
OS: Mac OS Catalina 10.15.4
Virtualbox: 6.1.6
Docker version 19.03.5

Description:
after running `vagrant up --provider virtual box 2019-box` 
and switching the docker context 
docker run shows the following error : Cannot connect to the Docker daemon at tcp://192.168.99.90:2376. Is the docker daemon running?.

I tried the following:
- Change the private ip address in the Vagrant file to 192.168.40.130 this did not work
- I RDP'd the guest and was able to ping the host 
- Switched off the firewall on the guest and from the guest tried to ping the box didn't work
- Tried to telnet the box on all ports didn't work
- Tried to do nmap -nP GUEST that also didn't work

PS: `docker-machine ls` shows the status  2019-box "Timedout" 

I ran out of options so I downgraded to version 5.2.26 and that fixed the issue.

now am having this issue 
```bash
2019-box   -        generic   Running   tcp://192.168.65.130:2376           Unknown   Unable to query docker version: 400 Bad Request: client version 1.15 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```
I know that this issue has been addresses  https://github.com/moby/moby/pull/28072.

**Comment by mohammadchehab** [comment]
Closing the issue, here 's what happened
brew cask uninstall virtualbox
went to virtualbox and downloaded the 5.2.26
vagrant up
then close virtualbox and  vagrant destroy
then upgrade virtualbox to 6.0.20
vagrant up
docker-machine ls now it;s working

**Comment by richard-mauri** [comment]
I followed the directions from: https://github.com/StefanScherer/windows-docker-machine
My goal was to try and get a windows docker container running on mac with vagrant+virtualbox

I installed latest vagrant (2.2.14) and virtualbox (6.1.18)

I get the same error as original poster.
What are the verion requirements?

```
OSXRMAURMBP16:windows-docker-machine rmauri$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
2019-box *          moby                2019-box windows-docker-machine           tcp://192.168.99.90:2376
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
OSXRMAURMBP16:windows-docker-machine rmauri$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           2019-box
 Experimental:      true
Cannot connect to the Docker daemon at tcp://192.168.99.90:2376. Is the docker daemon running?
```

**Comment by richard-mauri** [comment]
Please reopen
