### ISSUE TITLE
How to update a box?

### ISSUE THREAD

**Issue by srmo** [StefanScherer/windows-docker-machine#64]
Ahoi!

First, thank you for this great project which allows me to easily test windows containers on OSX.

Now my question: I've create a 2019 vm with docker a few months back and played around a bit. Now, I wanted to restart work on it but I'm wondering if there's anything I should and *can* do to update the box and the docker installation, as a few releases have happened in the meantime.
Please be aware that I'm relatively new to the vagrant/box setup stuff and only understand half of the techniques you use.

Looking forward to your advise!

**Comment by StefanScherer** [comment]
Hey @srmo Thank you, I‘m glad you like it. 

To update the best way is to re-run the packer build to have the latest Windows updates and base images pulled. 

For my public shared image on Vagrant Cloud you can skip the packer build. 

```
vagrant halt 2019-box
vagrant box update 2019-box
vagrant up 2019-box
vagrant box prune
```

As I assume the VM itself is ephemeral, we can just destroy it and replace it with a fresh one. 

That‘s how I do it from time to time.

**Comment by srmo** [comment]
Thanks for the input! I'm using the vanilla images, using packer. So I just rebuilt everything. Going to try your image for a change in the future. Keep rockin!
