### ISSUE TITLE
Support kubernetes

### ISSUE THREAD

**Issue by tibcoplord** [StefanScherer/windows-docker-machine#66]
Is there a way to support basic kubernetes ?  ie similar to the kubernetes tickbox in docker for desktop ?  

Thanks.

**Comment by StefanScherer** [comment]
Kubernetes is much heavier to setup a test environment. You would need a Linux box to run Kuberenetes and then add Windows as a worker node.
This is out of the scope of this project.

**Comment by StefanScherer** [comment]
You may have a look at the repo https://github.com/PatrickLang/windows-k8s-lab
