### ISSUE TITLE
Disable Autostart for 2016 and 2016-box

### ISSUE THREAD

**Issue by jantimon** [StefanScherer/windows-docker-machine#68]
Hey @StefanScherer 

I saw that for  2016 and 2016-box the `autostart: false` is missing:

https://github.com/StefanScherer/windows-docker-machine/blob/ae785e266905f12578c96fa6d4f1a73dd17f057b/Vagrantfile#L13-L21

Was that done on purpose or should I create a PR to fix that?

**Comment by StefanScherer** [comment]
Good catch. A PR is fine to disable autostart. Thanks.

**Comment by StefanScherer** [comment]
Fixed with #71
