### ISSUE TITLE
macOS - Waiting for WinRM to become available

### ISSUE THREAD

**Issue by mdhornet90** [StefanScherer/windows-docker-machine#7]
Setup:

Vagrant: v2.0.0
Packer: v1.1.1
Virtualbox: v5.2.0

Procedure:
I attempted to follow the substeps of Step 1, and got as far as `packer build --only=virtualbox-iso windows_2016_docker.json`. 

From there, a VM was created, windows was installed from the downloaded iso, and the installed Windows Guest OS appeared to log into a user called "Vagrant" and run a lot of startup scripts. It gets as far as the "Checking Windows Updates" script and does not seem to finish. On the macOS side, the script continues to hang at the "Waiting for WinRM to become available...", meaning I can't input the final `vagrant box add...` command.

I'm assuming I screwed something up, but I can't see where that might be the case. Perhaps the new major version of Vagrant isn't playing nicely with the install? Any help would be really appreciated, thank you!

Update:
I downgraded to Vagrant 1.9.2 and I'm no longer seeing a script that hangs without end, it looks like it actually makes progress downloading the updates.

**Comment by mdhornet90** [comment]
More info:
~After downgrading to Vagrant 1.9.2, it appears to apply updates to the VM, but I still end up seeing "Waiting for WinRM to become available..." after the guest OS has restarted one last time.~

It looks like WinRM connected and has continued processing, sorry to bother you!

**Comment by StefanScherer** [comment]
@mdhornet90 I also struggle with the win-updates.ps1 script right now. The latest cumulative update 2017-10 cannot be installed with the steps in win-updates.ps1. So the script tries again and again.
What you can do right now is after a reboot, just close the PowerShell terminal, open regedit and remove the registry key "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\InstallWindowsUpdates", then open a PowerShell terminal and type `a:\enable-winrm.ps1`. After a while the packer build can connect through WinRM and do the final provisioning.

**Comment by StefanScherer** [comment]
Caution, Vagrant does not support VirtualBox 5.2 right now -> https://github.com/hashicorp/vagrant/issues/9090

**Comment by mdhornet90** [comment]
Something interesting to note, when I was accidentally using VirtualBox 5.2 in combination with Vagrant 1.9.2, I noticed that while the updates indeed failed to install before the first reboot, when Windows came back up it immediately launched the `enable-winrm.ps1` by itself, no modification of the registry necessary.

**Comment by StefanScherer** [comment]
Is this still an issue?

**Comment by mdhornet90** [comment]
I unfortunately haven't checked this since late October; I ended up moving away from a Docker-based solution for my particular problem.

**Comment by StefanScherer** [comment]
No problem. Closing now as my last build about a week ago worked fine for VBox 5.1.x.

**Comment by olimcc** [comment]
This was an issue for me. I followed @StefanScherer steps successfully.

Notes:
During step: packer build --only=virtualbox-iso windows_2016_docker.json
Virtualbox version: 5.1.26

Notes: 
1. After executing `a:\enable-winrm.ps1` the machine did a couple of things and self restarted. It took about 5-8 minutes to see: 
```
    virtualbox-iso: #< CLIXML
    virtualbox-iso: WinRM connected.
    ...
```
2.  Type `powershell` at the prompt to open a PowerShell terminal before typing `a:\enable-winrm.ps1`.
