### ISSUE TITLE
Document the step to remove it

### ISSUE THREAD

**Issue by vmassol** [StefanScherer/windows-docker-machine#73]
Hi,

Thanks for your tutorial, it works great! I'd like to know how to decommission it if I don't need it anymore, and free up space.

Would be awesome to have some instructions for that in the README.md.

Thanks!

**Comment by vmassol** [comment]
is it enough to:
* `vagrant box remove StefanScherer/windows_2019_docker`
* `docker context rm 2019-box`

?

**Comment by StefanScherer** [comment]
Thanks. Sure that makes sense to describe this. 

First you should remove the VM before removing the box. 

```
vagrant destroy -f
vagrant box remove StefanScherer/windows_2019_docker
docker context rm 2019-box
```

**Comment by vmassol** [comment]
ok thanks, too late, I've already done the other 2 commands! :-)
