### ISSUE TITLE
VirtualBox doesn't allow 192.168.99.0 subnet by default

### ISSUE THREAD

**Issue by jaraco** [StefanScherer/windows-docker-machine#79]
In [VB #20626](https://www.virtualbox.org/ticket/20626), I learned that with the release of VirtualBox 6.1.28 dropped support for host-only IP ranges outside of 192.168.56.0/21 ([more details here](https://www.virtualbox.org/manual/ch06.html#network_hostonly)).

The windows-docker-machine [uses 192.168.99.90](https://github.com/StefanScherer/windows-docker-machine/blob/f4908901365c59742a352355c2bab1003eec3930/Vagrantfile#L89), outside the default allowed range.

Due to [other issues on macOS Monterey](https://github.com/hashicorp/vagrant/issues/12557#issuecomment-958183899), it's not possible to downgrade Virtualbox, so the only available workaround seems to be to edit the allowed ranges by creating/amending `/etc/vbox/networks.conf` to add something like:

```
* 192.168.99.0/24 192.168.56.0/21
```

It would be nice if the machine/Vagrantfile could use an address that falls into the allowed ranges such that it works out of the box.

**Comment by jaraco** [comment]
I did also try applying this patch and it also seems to have worked around the issue:

```diff
$ git diff
diff --git a/Vagrantfile b/Vagrantfile
index c31e3e3..2ad69ed 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -86,7 +86,7 @@ Vagrant.configure("2") do |config|
     v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
     # Use the recommended paravirtualization interface for windows (hyperv) - requires VirtualBox 6
     v.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
-    override.vm.network :private_network, ip: "192.168.99.90", gateway: "192.168.99.1"
+    override.vm.network :private_network, ip: "192.168.59.90", gateway: "192.168.56.1"
   end
 
   config.vm.provider "hyperv" do |v|
```

I'm yet unsure if changing the address there is likely to have any repercussions, but at first glance, I'm able to spin up a Windows docker guest and it's able to reach the network.

**Comment by StefanScherer** [comment]
Thanks @jaraco for the report and your investigation. 
Can I encourage you to make a pull request? It looks good and would merge it if it helps on Monterey with latest VirtualBox.

**Comment by jaraco** [comment]
Submitted as #80.
