### ISSUE TITLE
Is there any image for Apple silicon M1 macOS?

### ISSUE THREAD

**Issue by warezio** [StefanScherer/windows-docker-machine#82]
I have tried on M1 mac, but I got errors about architecture.
I found the VMware Fusion Technical Preview version that supports arm architecture.
It works fine, but the packer build iso has not supported arm image as Windows Insider Preview ARM64.

Please let me know if there are any possible ways to run windows docker on M1 Mac.

**Comment by StefanScherer** [comment]
I don't think this will work. Parallels demonstrated that they can run Windows ARM64, but not x86_64. VMware the same, they don't run x86_64 ISO files on M1. And there are no Windows arm64 container images. These two worlds don‘t match.

**Comment by mjpieters** [comment]
> And there are no Windows arm64 container images

Actually, there is; the Windows 11 insider preview, https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewarm64

**Comment by jalexander-bb** [comment]
+1 need support for Windows ARM64, iso does exist, this issue should be reopened/revisited.

**Comment by jalexander-bb** [comment]
Vmware also support M1 now https://blogs.vmware.com/teamfusion/2021/09/fusion-for-m1-public-tech-preview-now-available.html
