### ISSUE TITLE
Automatic shutdown?

### ISSUE THREAD

**Issue by gabyx** [StefanScherer/windows-docker-machine#90]
Are there any automatic shutdown settings in the `2019-box`. Because when I build an image which takes some time on my mac , the VM suddenly stops. Is there something like idle-detection and then an immediate shutdown configured?

**Comment by amotl** [comment]
Hi Gabriel,

maybe your machine was low on battery, so that you have been tripped by VirtualBox hibernating its VMs?

With kind regards,
Andreas.

**Comment by gabyx** [comment]
Jeah, its strange. I think it was such an issue, or it was the RAM. I increased to 8gb... Now it seems fine.
