### ISSUE TITLE
RDP 3389, but got CMD console only

### ISSUE THREAD

**Issue by ozbillwang** [StefanScherer/windows-docker-machine#96]
Not sure this is the design, I have successfully started a box `vagrant up 2019-box` and I can RDP to it (localhost:3389), with `vagrant/vagrant`, 

But after login, I didn't see the windows login, but a CMD windows

![image](https://github.com/StefanScherer/windows-docker-machine/assets/8954908/4b3da2f7-589b-4b20-a1dd-4311eb2344ec)

**Comment by StefanScherer** [comment]
That's by design. It's based on a Windows Server Core, so you only see a CMD shell.
